const MAX_COLOURS = 256;
const BIG_VALUE = 1.45E11;
const SMALLEST = Number.MIN_VALUE;
var badNumber = Math.sqrt(-1);
console.log(badNumber);
var str = "a";
var str = str + "toz";
console.log(str);
console.log("The length of str is " + str.length);
var stmt1 = "Didn't I say, \"It's time for lunch.\"?";
console.log(stmt1);
console.log(`${stmt1}`);
var word = stmt1.slice(9,12);
console.log("The third word of stmt1 is " + word);
var stmt2 = stmt1.replace("lunch", "dinner");
console.log(stmt2);
console.log(stmt2.toLowerCase());
console.log(stmt2.toUpperCase());
