# Dockerfile for ICS 211 Lab 5 Node.js Server
# uses the latest minor and patch release
FROM node:6

# can be seen using docker inspect <image ID>
LABEL maintainer="Nathan Mackenzie ntmk@telus.net"

#adding browser sync
RUN npm install -g nodemon npm-check-updates
