--------------------------------------------------------
--  Constraints for Table LOTTO649
--------------------------------------------------------

  ALTER TABLE "LAB07"."LOTTO649" ADD PRIMARY KEY ("DRAWNBR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAB07"."LOTTO649" MODIFY ("NBRBONUS" NOT NULL ENABLE);
  ALTER TABLE "LAB07"."LOTTO649" MODIFY ("NBR06" NOT NULL ENABLE);
  ALTER TABLE "LAB07"."LOTTO649" MODIFY ("NBR05" NOT NULL ENABLE);
  ALTER TABLE "LAB07"."LOTTO649" MODIFY ("NBR04" NOT NULL ENABLE);
  ALTER TABLE "LAB07"."LOTTO649" MODIFY ("NBR03" NOT NULL ENABLE);
  ALTER TABLE "LAB07"."LOTTO649" MODIFY ("NBR02" NOT NULL ENABLE);
  ALTER TABLE "LAB07"."LOTTO649" MODIFY ("NBR01" NOT NULL ENABLE);
  ALTER TABLE "LAB07"."LOTTO649" MODIFY ("DRAWDATE" NOT NULL ENABLE);
  ALTER TABLE "LAB07"."LOTTO649" MODIFY ("DRAWNBR" NOT NULL ENABLE);
