OPTIONS (ERRORS=345)
LOAD DATA 
INFILE 'C:\Users\aceis\OneDrive\Documents\ICS212\lab7\Lotto649 Export Loader Format\LOTTO649_DATA_TABLE.ldr' "str '\r\n'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "NMACKENZI"."LOTTO649"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"DRAWNBR" ,
"DRAWDATE" DATE "YYYY-MM-DD HH24:MI:SS" ,
"NBR01" ,
"NBR02" ,
"NBR03" ,
"NBR04" ,
"NBR05" ,
"NBR06" ,
"NBRBONUS" )
